run:
	python main.py

test:
	python -m unittest discover -s tests

test-filter:
	python -m unittest discover -s tests -k test_resolve_search_user_if_search_word_without_accent_using_search_term_with_accent

